---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-agent
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops-agent-role
  namespace: default
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "delete", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-agent-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: devops-agent
  namespace: default
roleRef:
  kind: Role
  name: devops-agent-role
  apiGroup: rbac.authorization.k8s.io
